# Generated by Django 3.0.5 on 2021-08-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=200, verbose_name='Apellido paterno')),
                ('ap_materno', models.CharField(max_length=200, verbose_name='Apellido materno')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Metodos_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Metodo de pago',
                'verbose_name_plural': 'Metodos de pago',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=200, verbose_name='Apellido paterno')),
                ('ap_materno', models.CharField(max_length=200, verbose_name='Apellido materno')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Pago_honorarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('estatus', models.CharField(max_length=200, verbose_name='Estatus')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('Metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Metodos_pago', verbose_name='Metodo de pago')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Doctor', verbose_name='Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
