# Generated by Django 3.0.5 on 2021-08-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210809_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago_honorarios',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
