# Generated by Django 3.0.5 on 2021-08-09 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210809_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago_honorarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.date.today(), verbose_name='Fecha'),
        ),
    ]
