# Generated by Django 3.0.5 on 2021-08-10 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0007_auto_20210809_1439'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('estatus', models.CharField(max_length=200, verbose_name='Estatus')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('diagnostico', models.CharField(max_length=200, verbose_name='Diagnostico')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institucion')),
                ('Metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Metodos_pago', verbose_name='Metodo de pago')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Doctor', verbose_name='Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Paciente', verbose_name='Paciente')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposito',
                'verbose_name_plural': 'Depositos',
            },
        ),
    ]
